# Generated by Django 4.2.13 on 2024-05-14 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cpm', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('warning', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('bucket_length', models.IntegerField(default=1800)),
                ('app_starts', models.IntegerField(default=0)),
                ('past_buckets_avg', models.FloatField(default=0)),
            ],
        ),
    ]
